### ISSUE TITLE
Repeat style for each node

### ISSUE THREAD

**Issue by Milan9x** [jpablobr/css2sass#11]
Suppose a example of css 

.pagination ul > .disabled > span,
.pagination ul > .disabled > a,
.pagination ul > .disabled > a:hover,
.pagination ul > .disabled > a:focus {
  color: #ccc;
  background-color: transparent;
  cursor: default;
}

but it convert like this way to scss 

.pagination ul > .disabled > {
  span {
    color: #ccc;
    background-color: transparent;
    cursor: default;
  }
  a {
    color: #ccc;
    background-color: transparent;
    cursor: default;
    &:hover, &:focus {
      color: #ccc;
      background-color: transparent;
      cursor: default;
    }
  }
}

**Comment by jpablobr** [comment]
This is related to https://github.com/jpablobr/css2sass/issues/4.
