### ISSUE TITLE
Add 'Conversion Styles'

### ISSUE THREAD

**Issue by ricardozea** [jpablobr/css2sass#16]
Although not an issue per se, it would be nice to be able to choose a conversion (or compilation) style.

I usually create my rules in single line ("compact" style in Sass):

    .selector { property:value; property2:value; property3:value; }

It'd be nice if the converter could keep this format.

Great tool and Thanks for creating it.

**Comment by jpablobr** [comment]
This is related to https://github.com/jpablobr/css2sass/issues/4.
