### ISSUE TITLE
Add support for comments

### ISSUE THREAD

**Issue by elchininet** [jpablobr/css2sass#17]
I've tried to convert a css to sass with many comments inside, the comments are not converted in the right manner. Example:

/* Block comment
line
line
End block comment */

div{
	border: 10px; /* inline comment */
}

The result will be:

/* Block comment
 *line
 *line
 *End block comment

div
  border: 10px
  /* inline comment

And the previous code is wrong

Thanks in advance

**Comment by jpablobr** [comment]
This is similar to https://github.com/jpablobr/css2sass/issues/4.
