### ISSUE TITLE
Find the same selectors and combine into one statement

### ISSUE THREAD

**Issue by jamez14** [jpablobr/css2sass#18]
This may be a rather large undertaking, but I figured I'd mention it. Also I'd be willing to help out as much as I can with this, although I'm not sure if my Ruby skills will be able to take it on fully.

Anyway, it would be awesome if the converter could do something like this...

You paste in this css...
```
.btn {
    color: #fff;
    text-decoration: none;
}

.foo {
    background-color: #000;
}

.btn:hover {
    color: #ccc;
    text-decoration:underline;
}
```

and it would then give you an output of this (SCSS)

```
.btn {
    color: #fff;
    text-decoration: none;
    &:hover {
        color: #000;
        text-decoration: underline;
    }
}

.foo {
    background-color: #000;
}
```

Basically, if there was the same selector (`.btn` & `.btn:hover`) it would find that selector and pseudo-class and combine them into 1 single statement. I suppose this may be more prone to errors, but maybe there is a good, reliable way to do this.

Either way, thank you for creating this awesome tool!

**Comment by jpablobr** [comment]
Yeah, that would be quite a bit of work but still in the end css2sass mostly relies on the [Sass::css built in parser](https://github.com/nex3/sass/blob/master/lib/sass/css.rb#L14). (similar to this other issue https://github.com/jpablobr/css2sass/issues/4)
