### ISSUE TITLE
Not conver keyframes 

### ISSUE THREAD

**Issue by vladymy** [jpablobr/css2sass#22]
Hi! 

Firstly I would like to say that you did a great thing man! I like you css2sass so much!!!!! And use it from time to time. 
But recently I founded out that css2sass not convert keyframes for example try convert this code

    @keyframes throb {
        0% {
            transform: scale(1);
        }
        50% {
            transform: scale(0.8);
        }
        100% {
            transform: scale(1);
        }
    }

**Comment by jpablobr** [comment]
This is related to https://github.com/jpablobr/css2sass/issues/4 :/
