### ISSUE TITLE
css2sass gulp plugin

### ISSUE THREAD

**Issue by Prestapro** [jpablobr/css2sass#25]
Hi guys,
Really cool tool, I use it to clean up outdated SCSS code.

I do not know of any tool that would also work well with inheritance in Sass as yours.

But I have every time to insert a file in the web interface, and a lot of files.

Can I use your script in a gulp or any other task runner?

With respect,
Alexander.

**Comment by jpablobr** [comment]
Sorry, that's not supported. You could probably just use the sass gem itself and write a shell script for that.
