### ISSUE TITLE
Does not do SCSS

### ISSUE THREAD

**Issue by Jakobud** [jpablobr/css2sass#26]
Webpage says "CSS 2 SASS/SCSS CONVERTER" but it clearly does not do SCSS. All converted code is in SASS format. Not SCSS format. Is there some sort of hidden toggle/checkbox on the page for doing SCSS instead that I'm just not seeing?

**Comment by Jakobud** [comment]
Oh wow, just saw that if you hover over the convert button there is an option. Cool trick, but you should definitely make that more obvious from a UX standpoint. Very hidden and not obvious at all. Just a suggestion from a front-end developer. Thanks,

**Comment by jpablobr** [comment]
Can always submit a PR. Just a suggestion from an OS dev. Closing.
